const errorHandler = async (ctx, next) => {
    try {
        await next();
    } catch (err) {
        ctx.status = err.status || 500;
        ctx.body = err.expose ? err.message : 'An error occurred!';
    }
};

module.exports = errorHandler;

